#!/bin/sh -eu
set -o pipefail

envsubst '$BACKEND_HOST' < /etc/nginx/conf.d/global-settings.template > /etc/nginx/conf.d/global-settings.conf

if [ ! -z "${ENABLE_SSL}" ]; then
  echo "Enabling SSL"
  sed 's/#SSLONLY//g' /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/ssl.conf
  mkdir -p /etc/nginx/ssl

  if [ ! -z "${SSL_CERTIFICATE}" ]; then
    echo "${SSL_CERTIFICATE}" > /etc/nginx/ssl/domain.crt
  fi
  if [ ! -z "${SSL_PRIVATE_KEY}" ]; then
    echo "${SSL_PRIVATE_KEY}" > /etc/nginx/ssl/domain.key
  fi
fi

exec "$@"
